try atom mapping for missing atom in source
TypeChecked/alphabet-soup pull request #29
Opened 2019-08-09 20:45 UTC by jbwheatley

#8 attempts to use transmutations in scope when atoms/molecules in target are not present in source during mixing.

2019-08-12 10:09 UTC, mcgizzle requested changes

2019-08-12 10:09 UTC, mcgizzle commented on alphabet-soup/src/main/scala/io/typechecked/alphabetsoup/SelectOrTransmuteOrDefault.scala
> + * Tries to use SelectFromAtomised to produce a value U from L. If it fails, tries to find a default atom
Docstring should be updated

2019-08-13 10:13 UTC, jdrphillips commented on alphabet-soup/src/test/scala/io/typechecked/alphabetsoup/SelectOrTransmuteOrDefaultSpec.scala
> +  it should "try to perform transmutations before inserting defaults" in {
As discussed transmute and default cases should be swapped around

2019-08-13 10:14 UTC, jdrphillips commented on alphabet-soup/src/test/scala/io/typechecked/alphabetsoup/SelectOrTransmuteOrDefaultSpec.scala
> +  it should "for type not present select and map molecule functorally if there is a transmutation in scope" in {
It's not mapping the molecule functorally in this example

2019-08-13 10:15 UTC, jdrphillips commented on alphabet-soup/src/test/scala/io/typechecked/alphabetsoup/SelectOrTransmuteOrDefaultSpec.scala
> +  it should "for type not present select and map molecule functorally if there is a transmutation in scope" in {
Yes it is! Nevermind

2019-08-13 10:17 UTC, jdrphillips commented on alphabet-soup/src/test/scala/io/typechecked/alphabetsoup/SelectOrTransmuteOrDefaultSpec.scala
> +}
Could you add a case proving Transmutations are not transitive?

`Transumte[A, B]` and `Transmute[B, C]` does not allow you `Transmute[A, C]`

2019-08-13 10:18 UTC, jdrphillips commented on alphabet-soup/src/main/scala/io/typechecked/alphabetsoup/SelectOrTransmuteOrDefault.scala
> +trait SelectOrTransmuteOrDefault[L, U] {
Renamed to match the new order of precedence

2019-08-13 10:18 UTC, jdrphillips commented on alphabet-soup/src/main/scala/io/typechecked/alphabetsoup/SelectAndTransmute.scala
> +object SelectAndTransmute extends LowPrioritySelectAndTransmute {
Could this be named `SelectTransmuted`?

2019-08-13 13:36 UTC, jdrphillips commented on alphabet-soup/src/main/scala/io/typechecked/alphabetsoup/Mixer.scala
> +                                                       implicit atom: Atom[BH],
Jack 😭

2019-08-13 13:39 UTC, jdrphillips approved these changes

2019-08-13 13:48 UTC, mcgizzle approved these changes

2019-08-13 13:49 UTC, merged